#!/bin/bash
# bootstrap odin
# assume-role to the correct account
set -e

./scripts/build_lambda_zip

PROJECT_NAME=${PROJECT_NAME:-coinbase/odin}
STEP_NAME=$(echo $PROJECT_NAME | sed 's/\//\-/')
echo $PROJECT_NAME
echo $STEP_NAME

step bootstrap                         \
  -lambda  $STEP_NAME    \
  -step    $STEP_NAME    \
  -states "$(go run odin.go json)" \
  -project $PROJECT_NAME \
  -config "development"

rm lambda.zip
